# Generated by Django 4.2.7 on 2026-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Management', 'Management'), ('Other', 'Other')], max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('feedback_score', models.FloatField(default=0.0, help_text='Student feedback score (0–10)')),
                ('performance_score', models.FloatField(default=0.0, help_text='Overall performance score (0–100)')),
                ('attendance_percentage', models.FloatField(default=0.0, help_text='Attendance percentage (0–100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['-created_at'],
            },
        ),
    ]
